### POST request add song
POST http://127.0.0.1:50081/add-song
Content-Type: application/json

{
  "name": "test4",
  "duration": 4
}

### GET request get current song
GET http://127.0.0.1:50081/get-song?name=test3
Accept: application/json


### POST request play songs
POST http://127.0.0.1:50081/play
Content-Type: application/json

### POST request jump to next song
POST http://127.0.0.1:50081/next
Content-Type: application/json

### POST request jump to prev song
POST http://127.0.0.1:50081/prev
Content-Type: application/json

### POST request jump to update err
POST http://127.0.0.1:50081/update-song
Content-Type: application/json

{
  "oldname": "te1",
  "newname": "test222"
}

### POST request jump to update
POST http://127.0.0.1:50081/update-song
Content-Type: application/json

{
  "oldname": "test",
  "newname": "test333"
}

### POST request jump to delete
POST http://127.0.0.1:50081/delete-song
Content-Type: application/json

{
  "name": "test4"
}