### POST request add song
POST http://127.0.0.1:50081/add-song
Content-Type: application/json

{
  "name": "test",
  "duration": 21
}

### GET request get current song
GET http://127.0.0.1:50081/get-song?name=test3
Accept: application/json


### PATCH request update song
PATCH localhost:50081/update
Content-Type: application/json

{
  "old_name": "test",
  "new_name": "test2"
}

### POST request play songs
POST http://127.0.0.1:50081/play
Content-Type: application/json

### POST request jump to next song
POST http://127.0.0.1:50081/next
Content-Type: application/json

### POST request jump to prev song
POST http://127.0.0.1:50081/prev
Content-Type: application/json

### POST request jump to prev song
POST http://127.0.0.1:50081/update-song
Content-Type: application/json

{
  "oldname": "test",
  "newname": "test222"
}
